package com.example.utils

/**
 * PhoneNumberUtils.kt
 *
 * PURPOSE:
 * Normalizes and secures phone numbers.
 *
 * WHY IT EXISTS:
 * Standardizes messy caller ID strings into E.164 format and applies SHA-256 hashing.
 * This ensures that NO raw phone numbers are ever saved to the local database or
 * uploaded to the Swarm Server, guaranteeing strict user privacy.
 */
object PhoneNumberUtils {

    /**
     * Normalizes a phone number by stripping all non-digit characters except standard plus prefix,
     * removing country prefixes (e.g., +91 or 91) to match locally against databases.
     */
    fun normalize(phoneNumber: String): String {
        val sanitized = phoneNumber.replace(Regex("[^0-9]"), "")
        // Handle Indian local formatting standard adjustments (+91 or 91 prefix)
        return when {
            sanitized.startsWith("91") && sanitized.length > 10 -> sanitized.substring(2)
            sanitized.length > 10 -> sanitized.takeLast(10)
            else -> sanitized
        }
    }

    /**
     * Checks if two phone numbers match after normalization.
     */
    fun areEqual(number1: String, number2: String): Boolean {
        return normalize(number1) == normalize(number2)
    }

    /**
     * DPDP Compliant AES-256-GCM Encryption
     * Replaces the old SHA-256 one-way hash so the central server can decrypt blocklisted numbers.
     */
    fun encrypt(number: String): String {
        try {
            val normalized = normalize(number)

            // 1. Fetch 32-byte Pepper from C++ Vault
            val pepperKey = com.example.security.NativeSecrets.getTelemetryPepper()
            val secretKey = javax.crypto.spec.SecretKeySpec(pepperKey, "AES")

            // 2. Generate dynamic 12-byte IV (Salt) to prevent replay attacks
            val iv = ByteArray(12)
            java.security.SecureRandom().nextBytes(iv)
            val gcmSpec = javax.crypto.spec.GCMParameterSpec(128, iv)

            // 3. Encrypt payload
            val cipher = javax.crypto.Cipher.getInstance("AES/GCM/NoPadding")
            cipher.init(javax.crypto.Cipher.ENCRYPT_MODE, secretKey, gcmSpec)
            val cipherText = cipher.doFinal(normalized.toByteArray(Charsets.UTF_8))

            // 4. Prepend IV to ciphertext and Base64 encode for HTTP transport
            val combined = ByteArray(iv.size + cipherText.size)
            System.arraycopy(iv, 0, combined, 0, iv.size)
            System.arraycopy(cipherText, 0, combined, iv.size, cipherText.size)

            return android.util.Base64.encodeToString(combined, android.util.Base64.URL_SAFE or android.util.Base64.NO_WRAP)
        } catch (e: Exception) {
            // Fallback to basic hash if C++ vault fails (for backwards compatibility/safety)
            val bytes = java.security.MessageDigest.getInstance("SHA-256").digest(normalize(number).toByteArray())
            return bytes.joinToString("") { "%02x".format(it) }.take(16)
        }
    }

    /**
     * Anti-Spoofing App HMAC Signature
     * Cryptographically proves to the server that this payload was generated by the genuine app,
     * not a hacker's python script, by signing it with the C++ Pepper.
     */
    fun generateAppSignature(payload: ByteArray): String {
        try {
            val pepperKey = com.example.security.NativeSecrets.getTelemetryPepper()
            val mac = javax.crypto.Mac.getInstance("HmacSHA256")
            val secretKey = javax.crypto.spec.SecretKeySpec(pepperKey, "HmacSHA256")
            mac.init(secretKey)

            val hmacBytes = mac.doFinal(payload)
            return android.util.Base64.encodeToString(hmacBytes, android.util.Base64.URL_SAFE or android.util.Base64.NO_WRAP)
        } catch (e: Exception) {
            return "signature_failed"
        }
    }
}
